### ISSUE TITLE
Could you provide built binary?

### ISSUE THREAD

**Issue by flo-at-work** [0x666690/ASPM#2]
Hello and thanks for this work!

Is there any chance you could provide a built binary of ASPMEnabler.efi for people who can't build it?

Best regards!

Edit: I just  saw that you already provided it in the other issue so I close this one.

**Comment by 0x666690** [comment]
Just commenting on this to say that I also put it out as a release just now. Should be much easier to find. 

https://github.com/0x666690/ASPM/releases/tag/v1.0.0
